version: "3.1"
services:
  spring-boot-docker-logging:
    image: spring-boot-docker-logging
    ports:
      - "8080:8080"
    networks:
      - elk
    volumes:
      - E:\data\logs:/logs
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.0
    ports:
      - "9200:9200"
    volumes:
      - E:\data\elasticsearch\elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - elk
      
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.1.0
    ports:
      - "5601:5601"
    volumes:
      - E:\data\kibana\kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - elk
  
  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.1.0
    volumes:
      - E:\data\logstash\logstash.yml:/usr/share/logstash/config/logstash.yml
      - E:\data\logstash\pipelines.yml:/usr/share/logstash/config/pipelines.yml
    networks:
      - elk
     
networks:
  elk: