version: "2.0"
services:
#  spring-boot-docker-logging:
#    image: spring-boot-docker-logging
#    ports:
#      - "8080:8080"
#    networks:
#      - elk
#    volumes:
#      - logs:/logs

  kibana:
    build:
      context: config/kibana
    ports:
      - "5601:5601"
    networks:
      - elk

  elasticsearch:
    build:
      context: config/elasticsearch
    ports:
      - "9200:9200"
    networks:
      - elk

  logstash:
    build:
      context: config/logstash
    networks:
      - elk
     
networks:
  elk: